#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 08 19:25:50 IST 2025
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1744120400936
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1744120400959
maven-metadata-snapshots.repo.egovernments.org.xml/@default-snapshots.repo.egovernments.org-https\://pmidc-nexus.lgpunjab.gov.in/nexus/content/repositories/snapshots/.lastUpdated=1744120550479
maven-metadata-snapshots.repo.egovernments.org.xml.error=Could not transfer metadata org.egov.services\:services-common\:1.1.0-SNAPSHOT/maven-metadata.xml from/to snapshots.repo.egovernments.org (https\://pmidc-nexus.lgpunjab.gov.in/nexus/content/repositories/snapshots/)\: Connect timed out
maven-metadata-repo.egovernments.org.xml.lastUpdated=1744120400935
maven-metadata-repo.egovernments.org.xml.error=
