#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 21:41:04 IST 2026
maven-metadata-AsposeJavaAPI.xml.error=
maven-metadata-JBoss\ Repository.xml.lastUpdated=1773119788909
maven-metadata-repo.egovernments.org.xml/@default-repo.egovernments.org-http\://repo.egovernments.org/nexus/content/groups/public/.lastUpdated=1773153289767
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-javaxt.com.xml.lastUpdated=1773119788959
maven-metadata-repo.egovernments.org.xml.lastUpdated=1773159064490
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-javaxt.com.xml.error=
maven-metadata-JSPRESSO.xml.lastUpdated=1773119804575
maven-metadata-AsposeJavaAPI.xml.lastUpdated=1773159047636
