#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 21:41:04 IST 2026
maven-metadata-AsposeJavaAPI.xml.error=
maven-metadata-JBoss\ Repository.xml.lastUpdated=1773119790110
maven-metadata-repo.egovernments.org.xml/@default-repo.egovernments.org-http\://repo.egovernments.org/nexus/content/groups/public/.lastUpdated=1773153495442
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-javaxt.com.xml.lastUpdated=1773119790144
maven-metadata-repo.egovernments.org.xml.lastUpdated=1773159064549
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-javaxt.com.xml.error=
maven-metadata-JSPRESSO.xml.lastUpdated=1773119807684
maven-metadata-AsposeJavaAPI.xml.lastUpdated=1773159047918
