#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 10:46:39 IST 2026
maven-metadata-jfrog-snapshot.xml.lastUpdated=1757695669130
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1773119799291
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1771913009207
maven-metadata-repo.digit.org.xml.lastUpdated=1749536244578
maven-metadata-repo.egovernments.org.xml.lastUpdated=1773119799290
maven-metadata-jfrog-release.xml.error=
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-jfrog-release.xml.lastUpdated=1757695668999
