#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Sep 16 21:07:03 IST 2025
maven-metadata-JBoss\ Repository.xml.lastUpdated=1758037023138
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-repo.egovernments.org.xml.lastUpdated=1758037023136
maven-metadata-JSPRESSO.xml.lastUpdated=1758037023176
