#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 10:46:38 IST 2026
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1773119798455
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1771913006756
maven-metadata-JBoss\ Repository.xml.lastUpdated=1752254963300
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-repo.egovernments.org.xml.lastUpdated=1773119798454
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-JSPRESSO.xml.lastUpdated=1752254963311
