#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jan 02 16:21:41 IST 2025
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1735815101758
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1735815101776
maven-metadata-repo.egovernments.org.xml.lastUpdated=1735815101757
maven-metadata-repo.egovernments.org.xml.error=
