#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 03 14:08:15 IST 2026
maven-metadata-AsposeJavaAPI.xml.error=
maven-metadata-JBoss\ Repository.xml.lastUpdated=1772524663086
maven-metadata-repo.egovernments.org.xml/@default-repo.egovernments.org-http\://repo.egovernments.org/nexus/content/groups/public/.lastUpdated=1772524663085
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-javaxt.com.xml.lastUpdated=1772524663125
maven-metadata-repo.egovernments.org.xml.lastUpdated=1772527095337
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-javaxt.com.xml.error=
maven-metadata-AsposeJavaAPI.xml.lastUpdated=1772524663109
