#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jan 02 16:24:55 IST 2025
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1735815295398
maven-metadata-repo.egovernments.org.xml.lastUpdated=1735815295397
maven-metadata-repo.egovernments.org.xml.error=
