#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Mar 10 21:40:51 IST 2026
maven-metadata-jfrog-snapshot.xml.lastUpdated=1773156578860
maven-metadata-AsposeJavaAPI.xml.error=
maven-metadata-JBoss\ Repository.xml.lastUpdated=1773119795124
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-javaxt.com.xml.lastUpdated=1773119795162
maven-metadata-repo.egovernments.org.xml.lastUpdated=1773159050998
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-jfrog-snapshot.xml.error=
maven-metadata-repo.egovernments.org.xml/@default-repo.egovernments.org-http\://repo.egovernments.org/nexus/content/groups/public/.lastUpdated=1773153905777
maven-metadata-jfrog-release.xml.error=
maven-metadata-javaxt.com.xml.error=
maven-metadata-JSPRESSO.xml.lastUpdated=1773156611377
maven-metadata-jfrog-release.xml.lastUpdated=1773156578850
maven-metadata-AsposeJavaAPI.xml.lastUpdated=1773159051003
