#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Sep 12 22:19:28 IST 2025
maven-metadata-jfrog-snapshot.xml.lastUpdated=1757695768753
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1744120600142
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1744120600178
maven-metadata-repo.digit.org.xml.lastUpdated=1744120600103
maven-metadata-repo.egovernments.org.xml.lastUpdated=1744120600105
maven-metadata-jfrog-release.xml.error=
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-jfrog-release.xml.lastUpdated=1757695768749
