#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 08 19:24:09 IST 2025
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1744120449590
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1744120449612
maven-metadata-repo.egovernments.org.xml.lastUpdated=1744120449588
maven-metadata-repo.egovernments.org.xml.error=
