#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Feb 13 18:30:15 IST 2026
maven-metadata-JBoss\ Repository.xml.lastUpdated=1770987615716
maven-metadata-repo.egovernments.org.xml/@default-repo.egovernments.org-http\://repo.egovernments.org/nexus/content/groups/public/.lastUpdated=1770987615712
maven-metadata-JBoss\ Repository.xml.error=
maven-metadata-repo.egovernments.org.xml.error=Could not transfer metadata org.egov\:egov-config\:BPA-3.0.0-SNAPSHOT/maven-metadata.xml from/to repo.egovernments.org (http\://repo.egovernments.org/nexus/content/groups/public/)\: Connect timed out
maven-metadata-JSPRESSO.xml.lastUpdated=1770987615762
