#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Sep 12 22:19:31 IST 2025
maven-metadata-jfrog-snapshot.xml.lastUpdated=1757695771314
maven-metadata-repo.egovernments.org.snapshots.xml.lastUpdated=1744120700805
maven-metadata-repo.egovernments.org.public.xml.lastUpdated=1744120700845
maven-metadata-snapshots.repo.egovernments.org.xml/@default-snapshots.repo.egovernments.org-https\://pmidc-nexus.lgpunjab.gov.in/nexus/content/repositories/snapshots/.lastUpdated=1744120700885
maven-metadata-repo.digit.org.xml.lastUpdated=1744120700739
maven-metadata-snapshots.repo.egovernments.org.xml.error=Could not transfer metadata org.egov.services\:tracer\:2.1.1-SNAPSHOT/maven-metadata.xml from/to snapshots.repo.egovernments.org (https\://pmidc-nexus.lgpunjab.gov.in/nexus/content/repositories/snapshots/)\: Connect timed out
maven-metadata-repo.egovernments.org.xml.lastUpdated=1744120700741
maven-metadata-jfrog-release.xml.error=
maven-metadata-repo.egovernments.org.xml.error=
maven-metadata-jfrog-release.xml.lastUpdated=1757695771312
